## Importing necessary modules and data

In [23]:
import numpy as np
import pandas as pd
import pickle
import sys
sys.path.append(r"D:\HopeAI\Assignments\MyModules")
import evaluate_clustering_algos as clust_algos
from sklearn.cluster import (KMeans, AgglomerativeClustering, SpectralClustering, Birch,
                             DBSCAN, OPTICS, AffinityPropagation, MeanShift)
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score
from sklearn.neighbors import NearestNeighbors
from kneed import KneeLocator
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

sns.set_theme('notebook')


In [20]:
filename=r"D:\HopeAI\Assignments\ML and DS Capstone\4. Feature Selection\dataset_unscaled.pkl"
dataset_unscaled = pickle.load(open(filename,'rb'))
dataset_unscaled


,Market Cap,Total_Annual_Return,Std_Monthly_Return,Max_Drawdown,Pos_Days_Pct,Avg_Daily_TR,Avg_Volume,Volume_Spike_Pct,Months_Pos_Pct,Beta_vs_NIFTY,Corr_with_NIFTY
0,2994291081216,84.785613,14.186042,22.867706,52.674897,2.352871,1.861417e+07,8.196721,63.636364,1.598832,0.426155
1,2994291081216,-37.685498,19.560876,68.997003,45.714286,3.742656,1.120364e+07,7.317073,54.545455,1.850348,0.457929
2,2994291081216,-14.119856,15.492383,34.794663,53.469388,1.581010,6.074467e+06,6.097561,54.545455,1.649825,0.597262
3,2994291081216,117.329561,8.526439,28.780005,56.680162,2.889061,1.295658e+07,8.064516,81.818182,1.912510,0.332076
4,2994291081216,78.500944,26.632411,43.633455,54.693878,6.293391,1.475299e+07,11.382114,36.363636,2.142941,0.478182
...,...,...,...,...,...,...,...,...,...,...,...
497,2532097654784,56.564122,11.196238,36.623083,52.000000,3.742075,2.239159e+07,9.163347,63.636364,0.670407,0.529060
498,2532097654784,84.735387,6.752821,12.734524,57.085020,6.545712,2.143325e+07,10.080645,72.727273,0.849918,0.476230
499,2532097654784,-44.808074,6.336069,47.492937,47.368421,4.864650,1.479087e+07,3.629032,27.272727,1.083736,0.691712
500,2532097654784,20.203754,6.272716,14.238744,48.360656,3.161690,1.015820e+07,6.938776,54.545455,1.108324,0.554158


## Scaling numeric columns

In [30]:
# Standardize using Standardscaler
scaler = StandardScaler()
dataset_scaled = scaler.fit_transform(dataset_unscaled)

dataset_scaled


array([[-0.34831857,  1.68056455,  1.57465965, ...,  0.38688169,
         1.57667863, -0.40235985],
       [-0.34831857, -1.66689527,  3.00788829, ..., -0.23110754,
         2.22244728, -0.19654005],
       [-0.34831857, -1.02278385,  1.92300265, ..., -0.23110754,
         1.70760195,  0.70600178],
       ...,
       [-0.47453835, -1.86157413, -0.51857813, ..., -2.08507525,
         0.25416209,  1.31781738],
       [-0.47453835, -0.08462869, -0.53547138, ..., -0.23110754,
         0.31729129,  0.42679132],
       [-0.47453835,  0.11668252, -0.37180118, ...,  1.00487093,
         0.18633209,  0.28775947]], shape=(484, 11))

In [33]:
print('Scores for Dataset scaled with StandardScaler\n')
df_scores = clust_algos.evaluate_clustering_algorithms(dataset_scaled, no_clust=3, rand_state=10, top_n=3)
df_scores


Scores for Dataset scaled with StandardScaler

                     Num_Clusters     Silhouette  DaviesBouldin  \
KMeans                        3.0         0.1311         1.9916   
Agglomerative                 3.0         0.1161         2.1816   
GaussianMixture               3.0         0.0265         3.5548   
SpectralClustering            3.0         0.1296         1.9256   
Birch                         3.0         0.1100         2.2831   
DBSCAN                        1.0  Not available  Not available   
OPTICS                        1.0  Not available  Not available   
AffinityPropagation          42.0         0.1075         1.4763   
MeanShift                     5.0         0.3378         1.1099   

                    CalinskiHarabasz  
KMeans                       77.2507  
Agglomerative                63.8260  
GaussianMixture              37.0697  
SpectralClustering           57.3853  
Birch                        60.6379  
DBSCAN                 Not available  
OPTICS   

,Num_Clusters,Silhouette,DaviesBouldin,CalinskiHarabasz
KMeans,3.0,0.1311,1.9916,77.2507
Agglomerative,3.0,0.1161,2.1816,63.8260
GaussianMixture,3.0,0.0265,3.5548,37.0697
SpectralClustering,3.0,0.1296,1.9256,57.3853
Birch,3.0,0.1100,2.2831,60.6379
DBSCAN,1.0,Not available,Not available,Not available
OPTICS,1.0,Not available,Not available,Not available
AffinityPropagation,42.0,0.1075,1.4763,29.9700
MeanShift,5.0,0.3378,1.1099,21.2880


In [34]:
# Standardize using MinMaxScaler
scaler = MinMaxScaler()
dataset_scaled = scaler.fit_transform(dataset_unscaled)

dataset_scaled


array([[0.1101939 , 0.46846779, 0.47663295, ..., 0.55555556, 0.53088626,
        0.44489057],
       [0.1101939 , 0.07030888, 0.69874747, ..., 0.44444444, 0.6226675 ,
        0.48710729],
       [0.1101939 , 0.14692181, 0.53061738, ..., 0.44444444, 0.54949402,
        0.67223213],
       ...,
       [0.08394156, 0.04715308, 0.15223356, ..., 0.11111111, 0.34292081,
        0.79772467],
       [0.08394156, 0.25850936, 0.14961553, ..., 0.44444444, 0.35189318,
        0.61496189],
       [0.08394156, 0.28245404, 0.17498031, ..., 0.66666667, 0.33328033,
        0.58644438]], shape=(484, 11))

In [35]:
print('Scores for Dataset scaled with MinMaxScaler\n')

df_scores = clust_algos.evaluate_clustering_algorithms(dataset_scaled, no_clust=3, rand_state=10, top_n=3)
df_scores


Scores for Dataset scaled with MinMaxScaler

                     Num_Clusters     Silhouette  DaviesBouldin  \
KMeans                        3.0         0.1848         1.7316   
Agglomerative                 3.0         0.1867         1.7685   
GaussianMixture               3.0         0.0348         3.2325   
SpectralClustering            3.0         0.1667         1.7369   
Birch                         3.0         0.2556         1.3659   
DBSCAN                        1.0  Not available  Not available   
OPTICS                        1.0  Not available  Not available   
AffinityPropagation          42.0         0.1052         1.5302   
MeanShift                     4.0         0.3593         1.3678   

                    CalinskiHarabasz  
KMeans                       92.6810  
Agglomerative                71.1717  
GaussianMixture              33.6888  
SpectralClustering           84.1235  
Birch                        59.1098  
DBSCAN                 Not available  
OPTICS     

,Num_Clusters,Silhouette,DaviesBouldin,CalinskiHarabasz
KMeans,3.0,0.1848,1.7316,92.6810
Agglomerative,3.0,0.1867,1.7685,71.1717
GaussianMixture,3.0,0.0348,3.2325,33.6888
SpectralClustering,3.0,0.1667,1.7369,84.1235
Birch,3.0,0.2556,1.3659,59.1098
DBSCAN,1.0,Not available,Not available,Not available
OPTICS,1.0,Not available,Not available,Not available
AffinityPropagation,42.0,0.1052,1.5302,30.2651
MeanShift,4.0,0.3593,1.3678,16.5225


In [36]:
# Standardize using RobustScaler
scaler = RobustScaler()
dataset_scaled = scaler.fit_transform(dataset_unscaled)

dataset_scaled


array([[-0.01585248,  1.78455141,  2.00138868, ...,  0.5       ,
         1.20055983, -0.34570011],
       [-0.01585248, -1.3764908 ,  3.5835421 , ...,  0.        ,
         1.67576192, -0.20341348],
       [-0.01585248, -0.76824948,  2.38592752, ...,  0.        ,
         1.29690244,  0.42052859],
       ...,
       [-0.17661286, -1.56032813, -0.30935448, ..., -1.5       ,
         0.22735895,  0.84348681],
       [-0.17661286,  0.1176605 , -0.32800309, ...,  0.        ,
         0.27381386,  0.22750579],
       [-0.17661286,  0.30776083, -0.14732615, ...,  1.        ,
         0.17744486,  0.13139078]], shape=(484, 11))

In [38]:
print('Scores for Dataset scaled with RobustScaler\n')
df_scores = clust_algos.evaluate_clustering_algorithms(dataset_scaled, no_clust=3, rand_state=10, top_n=3)
df_scores


Scores for Dataset scaled with RobustScaler

                     Num_Clusters     Silhouette  DaviesBouldin  \
KMeans                        3.0         0.2400         1.3196   
Agglomerative                 3.0         0.2964         1.1780   
GaussianMixture               3.0         0.1347         2.1783   
SpectralClustering            3.0         0.2338         1.2949   
Birch                         3.0         0.4729         0.8610   
DBSCAN                        1.0  Not available  Not available   
OPTICS                        1.0  Not available  Not available   
AffinityPropagation          44.0         0.1280         1.3525   
MeanShift                     8.0         0.3322         1.1067   

                    CalinskiHarabasz  
KMeans                       85.0425  
Agglomerative                92.9221  
GaussianMixture              57.0916  
SpectralClustering           74.0287  
Birch                        90.9201  
DBSCAN                 Not available  
OPTICS     

,Num_Clusters,Silhouette,DaviesBouldin,CalinskiHarabasz
KMeans,3.0,0.2400,1.3196,85.0425
Agglomerative,3.0,0.2964,1.1780,92.9221
GaussianMixture,3.0,0.1347,2.1783,57.0916
SpectralClustering,3.0,0.2338,1.2949,74.0287
Birch,3.0,0.4729,0.8610,90.9201
DBSCAN,1.0,Not available,Not available,Not available
OPTICS,1.0,Not available,Not available,Not available
AffinityPropagation,44.0,0.1280,1.3525,42.3760
MeanShift,8.0,0.3322,1.1067,29.8901
