In [2]:
#1.Debug the given code
import pandas as pd

data = {'Feature1': ['10', '20', '30'],  # 'Thirty' is not a valid number
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].astype(int)  # Error: ValueError: invalid literal for int() with base 10: 'Thirty', Cannot convert 'Thirty' to int

print(df)



   Feature1  Feature2
0        10       5.5
1        20       6.7
2        30       8.9


In [ ]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value, inplace=True)  # Error: fillna() does not modify in place -- inplace is added

print(df)


     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [ ]:
# 3.
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5]).reshape(-1,1)  # Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)


LinearRegression()

In [13]:
# 4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50]).reshape(-1,1)  # Error: Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [ ]:
#5.
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
# y = ['yes', 'no', 'yes']  # Error: Labels should be numeric
y = [1, 0, 1]  

model = LogisticRegression()
model.fit(X, y)


LogisticRegression()

In [ ]:
#6.
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})
df_cat = df[['Category']]
encoder = OneHotEncoder(sparse_output=False) # Convert to dense array for easier printing, to treat each row as a separate category label
encoded = encoder.fit_transform(df_cat)  # Error: Data should be reshaped
print(encoded)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [7]:
#6.
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]  # ValueError: Found input variables with inconsistent numbers of samples: [4, 3]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [8]:
#7.
from sklearn.linear_model import LogisticRegression

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels

model = LogisticRegression()
model.fit(X_train, y_train)


LogisticRegression()

In [10]:
#8.
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])  # ValueError: Input X contains NaN. LinearRegression does not accept missing values encoded as NaN natively.
y_train = np.array([10, 20, 30])

# Fill missing values using mean of the column
imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)


model = LinearRegression()
model.fit(X_train_imputed, y_train)  


LinearRegression()

In [11]:
#9.
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed

model = DecisionTreeClassifier()
model.fit(X_train, y_train)


DecisionTreeClassifier()

In [21]:
#10.
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)

model = SVC()
model.fit(X_train_scaled, y_train)
inp = [[1, 150]]
sc_inp = sc.transform(inp)
print(model.predict(sc_inp))  # Unreliable output due to large-scale difference


[0]
