In [ ]:
#1.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]

rfe = RFE(estimator=LogisticRegression(), n_features_to_select=1)
X_new = rfe.fit_transform(X, y)
X_new


array([[2],
       [4],
       [6]])

In [4]:
#2. ValueError: No feature in X meets the variance threshold 0.10000
from sklearn.feature_selection import VarianceThreshold

# Features should have non zero values
X = [[1, 2, 0], [0, 5, 1], [4, 3, 0]]
selector = VarianceThreshold(threshold=0.1)
X_new = selector.fit_transform(X)
X_new


array([[1, 2, 0],
       [0, 5, 1],
       [4, 3, 0]])

In [ ]:
#3.
from sklearn.metrics.pairwise import cosine_similarity
data = [[5, 0, 3], [0, 0, 0]]
similarity = cosine_similarity(data)
similarity


array([[1., 0.],
       [0., 0.]])

In [ ]:
#4.
from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]
selector = SelectFromModel(DecisionTreeClassifier(), threshold="mean")
X_new = selector.fit_transform(X, y)
X_new


array([[2],
       [4],
       [6]])

In [12]:
#5.KeyError: 'rating'
import pandas as pd
data = pd.DataFrame({
    'user': ['A', 'B', 'A'],
    'item': ['I1', 'I2', 'I2'],
    'rating': [5, 4, 3]
})
pivot = data.pivot(index='user', columns='item', values='rating') # rename rate to rating
pivot


item,I1,I2
user,,
A,5.0,3.0
B,NaN,4.0


In [ ]:
#6.ValueError: n_components=3 must be between 0 and min(n_samples, n_features)=2 with svd_solver='full'
from sklearn.decomposition import PCA
import numpy as np

X = np.array([[1, 2], [3, 4]])
pca = PCA(n_components=1) # Change n_components to 1
X_new = pca.fit_transform(X)
X_new


array([[-1.41421356],
       [ 1.41421356]])

In [ ]:
#7. ValueError: Input contains NaN.
ratings = pd.DataFrame({
    'User1': [5, None, 3],
    'User2': [None, 4, None],
    'User3': [1, 2, None]
})
ratings = np.nan_to_num(ratings)
sim = cosine_similarity(ratings.T)
sim


array([[1.        , 0.        , 0.38348249],
       [0.        , 1.        , 0.89442719],
       [0.38348249, 0.89442719, 1.        ]])

In [20]:
#8.
import numpy as np

user_vec = np.array([1, 2])
item_vec = np.array([0.5, 1.0])
score = np.dot(user_vec, item_vec)
print("Predicted Score:", score)


Predicted Score: 2.5


In [21]:
#9.
from sklearn.neighbors import NearestNeighbors
import numpy as np

X = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 1]])
model = NearestNeighbors()
model.fit(X)
distances, indices = model.kneighbors([X[0]], n_neighbors=2)
print(indices)


[[0 2]]


In [24]:
#10. ValueError: Expected 2D array, got 1D array instead:

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

a = np.array([1, 0, 1]).reshape(1,-1)
b = np.array([0, 1, 1]).reshape(1,-1)

sim = cosine_similarity(a, b)
print("Similarity:", sim)


Similarity: [[0.5]]
